"""add description and location to artisans

Revision ID: 057f83d3171f
Revises: 407798afbf18
Create Date: 2026-07-18 13:13:34.096121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057f83d3171f'
down_revision: Union[str, Sequence[str], None] = '407798afbf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artisans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('artisans', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artisans', 'location')
    op.drop_column('artisans', 'description')
    # ### end Alembic commands ###
