"""add product fields

Revision ID: 175e57780ab6
Revises: d1a52ae1bec2
Create Date: 2026-07-15 02:01:29.514954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175e57780ab6'
down_revision: Union[str, Sequence[str], None] = 'd1a52ae1bec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('artisan_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_products_artisan_id'), 'products', ['artisan_id'], unique=False)
    op.create_foreign_key(None, 'products', 'artisans', ['artisan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_artisan_id'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'artisan_id')
    # ### end Alembic commands ###
